### PR TITLE
include all the information into the image

### PR DESCRIPTION
**Pull request by harshad16**
include all the information into the image
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## Related Issues and Dependencies

Related-To: #14 

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

This change would get all the information into the notebook image.
Tested it, it does include everything and notebook seems to work by executing the cells.
some additional testing might be required later on.

### CODE REVIEW

**Review by durandom — APPROVED** [review]
I'm ok with this. See discussion in #14

**Comment by 4n4nd** [comment]
@harshad16 were you able to test the README generation with this? I think this might just overwrite an existing README file in the repo

**Comment by 4n4nd** [comment]
I think we should change the name for the generated README from `README.md` to `IMAGE_INFO.md` or something

**Comment by harshad16** [comment]
> @harshad16 were you able to test the README generation with this? I think this might just overwrite an existing README file in the repo

I thought i replied to this, yes I was able to test out the readme generation.

**Comment by 4n4nd** [comment]
@harshad16 can you please rename the `README.md` to something else?

**Comment by harshad16** [comment]
> @harshad16 can you please rename the `README.md` to something else?

will change that :+1:

**Pull request merged**
