### PR TITLE
Copy hidden files as well

### PR DESCRIPTION
**Pull request by tumido**
## Related Issues and Dependencies

Related to: #15 

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Some configuration files are usually hidden in dot folders or dot files. E.g https://github.com/aicoe-aiops/project-template/tree/master/.jupyter This change allows to backup/restore those files as well.

### CODE REVIEW

**Comment by tumido** [comment]
cc @4n4nd

**Comment by tumido** [comment]
btw, what is the content of the `/tmp/src/` folder anyways. Wouldn't my change copy a `.git` folder as well? Might that happen, is that folder present? I don't think we want to copy that particular folder though. Just a thought. :slightly_smiling_face:

**Comment by 4n4nd** [comment]
> btw, what is the content of the `/tmp/src/` folder anyways. Wouldn't my change copy a `.git` folder as well? Might that happen, is that folder present? I don't think we want to copy that particular folder though. Just a thought. slightly_smiling_face

The `/tmp/src` folder contains the contents of the repo and not the `.git` folder. I don't really know why but I just tested it.
So it should include all other hidden files :+1:

**Comment by 4n4nd** [comment]
Just for documentation, we will need to add `--exclude "" ` to be able to include the `.git` directory in the built image

**Pull request merged**
