### PR TITLE
setup repository to build multiple images

### LINKED ISSUE #3: Cannot find s2i-lab-elyra custom notebook source
**Describe the bug**
Cannot find source of the image: https://quay.io/repository/thoth-station/s2i-elyra-custom-notebook?tab=info

**To Reproduce**

**Expected behavior**
Repo for tracking build of this image.

**Screenshots**

**Additional context**

### LINKED ISSUE #18: Build s2i-custom-notebook image with different base images.
**Is your feature request related to a problem? Please describe.**
s2i-custom-notebook image is built with s2i-minimal-notebook which supports CPU architecture, enable s2i-custom-notebook to be built with GPU based base image for enabling it to support GPU architecture.

**Describe the solution you'd like**
Update the pipeline to build multiple images of s2i-custom-notebooks with different base images (CPU&GPU).

**Describe alternatives you've considered**
openshift buildconfigs with different base images initiated.

**Additional context**
Some of the projects requires GPU architecture, the GPU image is required for those project to function without environmental errors.

### PR DESCRIPTION
**Pull request by harshad16**
setup repository to build multiple images
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/support/issues/3
https://github.com/AICoE/s2i-custom-notebook/issues/18

## Description

This would allow developers to build multiple images at once.

### CODE REVIEW

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Comment by 4n4nd** [comment]
@harshad16 can you add a line in [the build instructions](https://github.com/AICoE/s2i-custom-notebook#build) that users can use a different base image for different python versions?

**Comment by 4n4nd** [comment]
@harshad16 can you also add the annotation for image name in [the README imagestream template](https://github.com/AICoE/s2i-custom-notebook#how-to-add-the-image-to-open-data-hubjupyterhub) ([example](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/additional/spark-scipy-notebook-imagestream.yaml#L6-L7))?

```yaml
annotations:
    opendatahub.io/notebook-image-name: "My Notebook Image with Python 3.6"
```

**Comment by harshad16** [comment]
Made all required changes.
Ready for review again @4n4nd

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Comment by harshad16** [comment]
/approve
this can go in

**Pull request merged**
